-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 19:16:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema photobucket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `photobucket` ;

-- -----------------------------------------------------
-- Schema photobucket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photobucket` DEFAULT CHARACTER SET utf8mb3 ;
USE `photobucket` ;

-- -----------------------------------------------------
-- Table `photobucket`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photobucket`.`album` ;

CREATE TABLE IF NOT EXISTS `photobucket`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `photobucket`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `photobucket`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photobucket`.`imagen` ;

CREATE TABLE IF NOT EXISTS `photobucket`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `album_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `url_s3` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_imagen_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `photobucket`.`album` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `photobucket`.`rostros_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photobucket`.`rostros_usuarios` ;

CREATE TABLE IF NOT EXISTS `photobucket`.`rostros_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `key_s3` VARCHAR(255) NOT NULL COMMENT 'ID de reconocimiento facial de AWS Rekognition',
  PRIMARY KEY (`id`),
  INDEX `fk_rostros_usuarios_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_rostros_usuarios_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `photobucket`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `photobucket`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photobucket`.`usuario` ;

CREATE TABLE IF NOT EXISTS `photobucket`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `url_foto` VARCHAR(200) NOT NULL,
  `face_id_habilitado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'No existe el boolean entonces usar 1 o 0',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;